"""Specialty Books models - re-export all models."""
from app.modules.specialty.models.enums import (
    AgeRange,
    AnswerKeyPosition,
    AssetType,
    Audience,
    BatchStatus,
    BilingualLayout,
    BookStatus,
    BookType,
    ClueStyle,
    ColoringPageType,
    ColorPalette,
    Difficulty,
    DifficultyMode,
    DistributorName,
    FearIntensity,
    IllustrationStyle,
    ISBNStatus,
    LicenseType,
    LineStyle,
    PhotoUsageType,
    PageLayout,
    PreflightStatus,
    PuzzleType,
    StoryMode,
    TemplateType,
    TextPosition,
    VariantType,
    WordDifficulty,
    WordListSourceType,
)
from app.modules.specialty.models.childrens import (
    ChildrensBook,
    ChildrensBookCharacter,
    ChildrensBookPage,
)
from app.modules.specialty.models.coloring import (
    ColoringBook,
    ColoringBookPage,
)
from app.modules.specialty.models.puzzles import (
    Puzzle,
    PuzzleBook,
)
from app.modules.specialty.models.photo import (
    PhotoReference,
)
from app.modules.specialty.models.shared import (
    AccessibilityVariant,
    AssetProvenance,
    BackMatterTemplate,
    BatchJob,
    BookBundle,
    BookSeries,
    ContentFingerprint,
    DistributorPreflight,
    FontLicense,
    ISBNPool,
    OriginalityReport,
    WordListSource,
)

__all__ = [
    # Enums
    "AgeRange",
    "AnswerKeyPosition",
    "AssetType",
    "Audience",
    "BatchStatus",
    "BilingualLayout",
    "BookStatus",
    "BookType",
    "ClueStyle",
    "ColoringPageType",
    "ColorPalette",
    "Difficulty",
    "DifficultyMode",
    "DistributorName",
    "FearIntensity",
    "IllustrationStyle",
    "ISBNStatus",
    "LicenseType",
    "LineStyle",
    "PageLayout",
    "PhotoUsageType",
    "PreflightStatus",
    "PuzzleType",
    "StoryMode",
    "TemplateType",
    "TextPosition",
    "VariantType",
    "WordDifficulty",
    "WordListSourceType",
    # Children's Books
    "ChildrensBook",
    "ChildrensBookPage",
    "ChildrensBookCharacter",
    # Coloring Books
    "ColoringBook",
    "ColoringBookPage",
    # Puzzle Books
    "PuzzleBook",
    "Puzzle",
    # Photo References
    "PhotoReference",
    # Shared
    "AssetProvenance",
    "FontLicense",
    "BatchJob",
    "ContentFingerprint",
    "OriginalityReport",
    "BookSeries",
    "BackMatterTemplate",
    "ISBNPool",
    "DistributorPreflight",
    "BookBundle",
    "AccessibilityVariant",
    "WordListSource",
]
